name: Package Chrome extension zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Zip the files/folders you want to bundle
      - name: Zip selected files
        run: |
          zip -r namitab.zip \
            16x16.png \
            32x32.png \
            48x48.png \
            128x128.png \
            manifest.json \
            newtab.html \
            newtab.js \
            options.html \
            options.js

      # 3. Create a release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: namitab.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
